### 删除菜单
DELETE  http://localhost:3000/api/menu
Content-Type: application/json
Authorization: Bearer {{token}}

[14]

### 新增菜单
POST http://localhost:3000/api/menu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "用户中心",
  "pid": 0,
  "type": 2,
  "icon": "icon",
  "path": "/user",
  "component": "/sys/user",
  "perms":"",
  "sort": 1,
  "status": 1
}

### 菜单列表
GET  http://localhost:3000/api/menu
Content-Type: application/json
Authorization: Bearer {{token}}


### 删除角色
DELETE  http://localhost:3000/api/role
Content-Type: application/json
Authorization: Bearer {{token}}

[5]


### 新增角色
POST  http://localhost:3000/api/role
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "id": 1,
      "name": "研发",
      "menu_ids": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        14
      ]
    }

### 角色列表
GET http://localhost:3000/api/role?app_id=1&page=1&limit=10
Authorization: Bearer {{token}}


### 删除用户
DELETE   http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

[2]

### 新增用户
POST  http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "id": 1,
      "username": "admin",
      "password": "21232f297a57a5a743894a0e4a801fc3",
      "email": "",
      "mobile": "",
      "status": 1,
      "role_ids": [
        1,2
      ]
    }

### 用户列表
GET http://localhost:3000/api/user?app_id=1&page=1&limit=10
Authorization: Bearer {{token}}

### 当前用户信息
GET http://localhost:3000/api/user/current
Authorization: Bearer {{token}}


### 登录
POST  http://localhost:3000/x-admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### 
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI5ODU1MjMyLCJleHAiOjE3Mjk4NjI0MzJ9.e_CMlEcpUQTMSyarmBPZkXf5fYk3ijgztcBGCkzJuko