###
GET  http://localhost:3000/api/menu
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI5Nzc2ODY2LCJleHAiOjE3Mjk3ODQwNjZ9.D8r8OXdT9EZ-CTunEEv5UBxHjX6q9ciTUzS7DlFJ-pA


### 删除角色
DELETE  http://localhost:3000/api/role
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI1OTU4ODM0LCJleHAiOjE3MjU5NjYwMzR9.Bcvux9H5eRYX_Jk73gcF9tRWxOCcbRwLPhwUvpcmYNQ


###
POST  http://localhost:3000/api/role
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI1OTU4ODM0LCJleHAiOjE3MjU5NjYwMzR9.Bcvux9H5eRYX_Jk73gcF9tRWxOCcbRwLPhwUvpcmYNQ

{
  "app_id": 1,
  "name": "商务"
}

###
GET http://localhost:3000/api/role?app_id=1&page=1&limit=10
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI1OTU4ODM0LCJleHAiOjE3MjU5NjYwMzR9.Bcvux9H5eRYX_Jk73gcF9tRWxOCcbRwLPhwUvpcmYNQ


###
POST  http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI1OTU4ODM0LCJleHAiOjE3MjU5NjYwMzR9.Bcvux9H5eRYX_Jk73gcF9tRWxOCcbRwLPhwUvpcmYNQ

{
  "username": "guest2",
  "password": "guest2",
  "email": "aa",
  "mobile": "b",
  "status": 1
}

###
GET http://localhost:3000/api/user?app_id=1&page=1&limit=10
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI1OTU4ODM0LCJleHAiOjE3MjU5NjYwMzR9.Bcvux9H5eRYX_Jk73gcF9tRWxOCcbRwLPhwUvpcmYNQ

### 当前用户信息
GET http://localhost:3000/api/user/current
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzI5Nzc2ODY2LCJleHAiOjE3Mjk3ODQwNjZ9.D8r8OXdT9EZ-CTunEEv5UBxHjX6q9ciTUzS7DlFJ-pA


### 登录
POST  http://localhost:3000/login
Content-Type: application/json

{
  "app_id": 1,
  "username": "admin",
  "password": "admin"
}

